// Generated by CoffeeScript 1.8.0
(function() {
  var base, injectScript, logger, run, settrade, _$;

  _$ = jQuery.noConflict();

  base = {
    buy: function(_symbol, _volume, _price, _pin) {
      this.uiBuy();
      this.uiSymbol(_symbol);
      this.uiVolume(_volume);
      this.uiPrice(_price);
      this.uiPin(_pin);
      return this.uiSubmit();
    },
    sell: function(_symbol, _volume, _price, _pin) {
      this.uiSell();
      this.uiSymbol(_symbol);
      this.uiVolume(_volume);
      this.uiPrice(_price);
      this.uiPin(_pin);
      return this.uiSubmit();
    }
  };

  settrade = {
    uiBuy: function() {
      var side;
      side = _$('input.buyRadio').first();
      if (side.attr('name') === 'txtBorS') {
        return side.prop('checked', true);
      }
    },
    uiSell: function() {
      var side;
      side = _$('input.sellRadio').first();
      if (side.attr('name') === 'txtBorS') {
        return side.prop('checked', true);
      }
    },
    uiSymbol: function(_symbol) {
      var symbol;
      symbol = _$('input.symbol').eq(2);
      if (symbol.attr('name') === 'txtSymbol') {
        return symbol.val(_symbol);
      }
    },
    uiVolume: function(_volume) {
      var volume;
      volume = _$('input.volume').first();
      if (volume.attr('name') === 'txtQty') {
        return volume.val(_volume);
      }
    },
    uiPrice: function(_price) {
      var price;
      price = _$('input.price').first();
      if (price.attr('name') === 'txtPrice') {
        return price.val(_price);
      }
    },
    uiPin: function(_pin) {
      var pin;
      pin = _$('input.pin').first();
      if (pin.attr('name') === 'txtPIN_new') {
        return pin.val(_pin);
      }
    },
    uiSubmit: function() {
      return _$('input.submitBtn').first().click();
    }
  };

  _$.extend(settrade, base);

  run = function() {
    var ws;
    ws = new WebSocket('ws://0.0.0.0:8080');
    ws.onopen = function() {
      return ws.send('SAWASDEE');
    };
    return ws.onmessage = function(e) {
      var client, pin, signal;
      signal = JSON.parse(e.data);
      if (signal) {
        if (signal.side) {
          client = settrade;
          pin = atob('MDAwMDAw');
          if (signal.side === 'B') {
            client.buy(signal.symbol, signal.volume, signal.price, pin);
            return logger(1, signal);
          } else if (signal.side === 'S') {
            client.sell(signal.symbol, signal.volume, signal.price, pin);
            return logger(1, signal);
          }
        } else if (signal.code) {
          if (signal.code === 'WOR1') {
            return logger(0, "I'm working");
          } else if (signal.code === 'WOR3') {
            return ws.send('WOR4');
          }
        }
      }
    };
  };

  logger = function(level, msg) {
    if (level === 0) {
      return console.debug(new Date(), msg);
    } else if (level === 1) {
      return console.log(new Date(), msg);
    }
  };

  injectScript = function() {
    var script;
    script = document.createElement("script");
    script.type = "text/javascript";
    script.innerHTML = "window.confirm=function(){console.log('hey');return false};window.alert=function(){return false};";
    return document.getElementsByTagName("head")[0].appendChild(script);
  };

  _$(function() {
    return injectScript();
  });

}).call(this);
