// Generated by CoffeeScript 1.8.0
(function() {
  var fetch;

  fetch = function() {
    var cols, content, data, error, row, rows, symbol, _i, _len, _results;
    try {
      content = top.frames[1].document;
      rows = $(content).find('div.marketWatch').find('tr');
      _results = [];
      for (_i = 0, _len = rows.length; _i < _len; _i++) {
        row = rows[_i];
        cols = $(row).children('td');
        symbol = $.trim(cols.eq(0).text());
        if (symbol !== '' && symbol !== 'STOCK') {
          data = {
            symbol: symbol,
            bid_volume: cols.eq(2).text().replace(',', '').replace('T', '000'),
            bid_price: cols.eq(3).text().replace(',', ''),
            offer_price: cols.eq(5).text().replace(',', ''),
            offer_volume: cols.eq(6).text().replace(',', '').replace('T', '000'),
            last_price: cols.eq(7).text().replace(',', ''),
            client: 'klass_trade_client'
          };
          if (parseFloat(data.bid_price) > 0 && parseFloat(data.offer_price) > 0) {
            _results.push($.ajax({
              url: "https://localhost:4001/intraday-quotes/create",
              dataType: 'jsonp',
              data: data,
              success: function(data) {},
              error: function(data) {}
            }));
          } else {
            _results.push(void 0);
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    } catch (_error) {
      error = _error;
      return console.debug('Exception: ' + error);
    }
  };

}).call(this);
