source 'https://rubygems.org'

gem 'rails', '4.1.7'
gem 'pg'

gem 'sass-rails', '~> 4.0.3'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'bootstrap-sass'
gem 'slim-rails'
gem 'autoprefixer-rails'

group :development do
  gem 'spring'
  gem 'thin'
end

group :production do
  gem 'therubyracer'
end

gem 'draper'
gem 'em-websocket'
gem 'foreman'
gem 'kaminari'
gem 'talib_ruby'
gem 'ta-indicator'

gem 'set_scraper', '0.0.1', :path => './vendor/gems'
